# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "agldemo"
BBFILE_PATTERN_agldemo = "^${LAYERDIR}/"
BBFILE_PRIORITY_agldemo = "70"

BBFILES_DYNAMIC += " \
    meta-tensorflow:${LAYERDIR}/dynamic-layers/meta-tensorflow/*/*/*.bbappend \
    openembedded-layer:${LAYERDIR}/dynamic-layers/meta-oe/*/*/*.bbappend \
"

LICENSE_PATH += "${LAYERDIR}/licenses"

LAYERSERIES_COMPAT_agldemo = "wrynose"

LAYERDEPENDS_agldemo = "aglcore qt6-layer openembedded-layer networking-layer multimedia-layer flutter-layer meta-app-framework"

########### WORKAROUND FOR MESON and QT6 ############
QT6_INSTALL_LIBEXECDIR := "${bindir}"
